version: '3'
services:
  webdav:
    image: bytemark/webdav
    restart: always
    ports:
      - "80:80"
    environment:
      AUTH_TYPE: Digest
    volumes:
      - /srv/dav:/var/lib/dav
      - /home/loyxin/docker/webdav/user.passwd:/user.passwd

